Update to 0.12.1 tag
chevdor/subwasm pull request #11
Opened 2021-07-13 16:16 UTC by sacha-l

Updates the install command + other references to 0.12.0 tag.

2021-07-13 17:26 UTC, chevdor requested changes
Make sure all versions are bumped please

2021-07-13 17:26 UTC, chevdor commented on README.md
> +    wget https://github.com/chevdor/subwasm/releases/download/v0.12.0/subwasm_linux_amd64_v0.12.1 -O subwasm.deb
You missed one here :)

2021-07-14 08:35 UTC, sacha-l commented on README.md
> +    wget https://github.com/chevdor/subwasm/releases/download/v0.12.0/subwasm_linux_amd64_v0.12.1 -O subwasm.deb
Should be all good now.

2021-07-19 08:09 UTC, chevdor commented
So for this PR, the md should not be fixed, instead, the .adoc should be updated and you run `just md` to get the markdown version. The `asciidoc` version is less error prone (and prevent the misses you experienced) as it uses a variable. As far as updating the usages (which are `includes` in the asciidoc source), they can be refreshed by running `just doc` or `just usage`. Not only it will bump the versions but also ensure that the doc is in sync.

I will be pushing a new commit to your PR soon.

2021-07-19 08:11 UTC, merged